main: ru.civwars.CivWars
name: CivWars
description: This plugin does so much stuff it can't be contained!
author: Duox0
version: 1.0.0
api-version: 1.12.2
depend: [DatabaseAPI]
load: POSTWORLD
commands:
    test:
        aliases: [test]
    civcraft:
        aliases: [civcraft,cc]
    admin:
        aliases: [admin,ad]
    give:
        aliases: [give]
    show:
        aliases: [show] 
    balance:
        aliases: [balance,bal] 
    civ:
        aliases: [civ] 
    town:
        aliases: [town,t]
    mobs:
        mobs: [mobs]